// Auto-generated by scripts/generate-schema.ts — do not edit directly.
// Run `npm run config:generate` to regenerate after modifying schema source files.
//
// Input SHA: 02e61d4e942111ba
// Generated at: 2026-04-22T03:06:23.095Z

/* eslint-disable */
// prettier-ignore

/** Minimal JSON Schema node shape used in the generated output. */
export type JsonSchemaNode = {
  title?: string;
  description?: string;
  type?: string | string[];
  properties?: Record<string, JsonSchemaNode>;
  additionalProperties?: JsonSchemaNode | boolean;
  items?: JsonSchemaNode;
  anyOf?: JsonSchemaNode[];
  allOf?: JsonSchemaNode[];
  oneOf?: JsonSchemaNode[];
  enum?: unknown[];
  required?: string[];
  $schema?: string;
  [key: string]: unknown;
};

/** SHA-256 (first 16 hex chars) of the schema source files used as input. */
export const INPUT_SHA = '02e61d4e942111ba';

/** JSON Schema (Draft-07) for the complete Alduin YAML configuration. */
export const GENERATED_CONFIG_SCHEMA: JsonSchemaNode = {
  "type": "object",
  "properties": {
    "catalog_version": {
      "type": "string",
      "title": "Catalog Version",
      "description": "Model catalog revision this config was validated against. Set automatically by `alduin catalog sync`.",
      "x-alduin-advanced": true
    },
    "orchestrator": {
      "type": "object",
      "properties": {
        "model": {
          "type": "string",
          "pattern": "^\\w[\\w.-]*\\/[\\w][\\w.-]*$",
          "title": "Orchestrator Model",
          "description": "Fully-qualified model string (provider/name). Must appear in the active catalog."
        },
        "max_planning_tokens": {
          "type": "number",
          "exclusiveMinimum": 0,
          "title": "Max Planning Tokens",
          "description": "Maximum tokens the orchestrator may consume on a single planning call.",
          "x-alduin-advanced": true
        },
        "context_strategy": {
          "type": "string",
          "title": "Context Strategy",
          "description": "How the orchestrator manages its context window. \"sliding_window\" drops the oldest turns when the budget is full.",
          "x-alduin-advanced": true
        },
        "context_window": {
          "type": "number",
          "exclusiveMinimum": 0,
          "title": "Context Window (tokens)",
          "description": "Token budget for the orchestrator context. Should be ≤ the model's supported context length.",
          "x-alduin-advanced": true
        }
      },
      "required": [
        "model",
        "max_planning_tokens",
        "context_strategy",
        "context_window"
      ],
      "additionalProperties": false,
      "title": "Orchestrator",
      "description": "Planning model configuration. The orchestrator decomposes requests into steps but never executes them directly."
    },
    "executors": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "model": {
            "$ref": "#/properties/orchestrator/properties/model",
            "title": "Model",
            "description": "Fully-qualified model string for this executor."
          },
          "max_tokens": {
            "type": "number",
            "exclusiveMinimum": 0,
            "title": "Max Output Tokens",
            "description": "Maximum tokens the executor may generate per task."
          },
          "tools": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "default": [],
            "title": "Allowed Tools",
            "description": "Tool names this executor may call. An empty list means no tools.",
            "x-alduin-advanced": true
          },
          "context": {
            "type": "string",
            "enum": [
              "task_only",
              "task_plus_style_guide",
              "message_only"
            ],
            "title": "Context Mode",
            "description": "\"task_only\" — receives the task instruction only. \"task_plus_style_guide\" — also receives the style guide. \"message_only\" — receives the raw user message.",
            "x-alduin-advanced": true
          },
          "request_timeout_ms": {
            "type": "integer",
            "exclusiveMinimum": 0,
            "title": "Request Timeout (ms)",
            "description": "Per-request SDK timeout in milliseconds. Overrides the provider SDK default to prevent runaway requests.",
            "x-alduin-advanced": true
          }
        },
        "required": [
          "model",
          "max_tokens",
          "context"
        ],
        "additionalProperties": false,
        "title": "Executor",
        "description": "A single executor definition. Executors receive only the task instruction — no conversation history."
      },
      "title": "Executors",
      "description": "Named executor configurations. Each executor is a stateless model that performs a specific task type (code, research, content, …)."
    },
    "providers": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "api_key_env": {
            "type": "string",
            "title": "API Key Env Var",
            "description": "Name of the environment variable holding the API key. The value is never stored in config.",
            "x-alduin-sensitive": true
          },
          "base_url": {
            "type": "string",
            "format": "uri",
            "title": "Base URL",
            "description": "Override the provider's default API endpoint. Required for self-hosted or proxy deployments."
          },
          "api_type": {
            "type": "string",
            "title": "API Type",
            "description": "\"openai-compatible\" enables the OpenAI SDK with a custom base URL. Leave unset for native provider SDKs.",
            "x-alduin-advanced": true
          }
        },
        "additionalProperties": false,
        "title": "Provider",
        "description": "Configuration for a single LLM provider."
      },
      "title": "Providers",
      "description": "LLM provider configurations keyed by alias (e.g. \"anthropic\", \"openai\", \"ollama\")."
    },
    "routing": {
      "type": "object",
      "properties": {
        "pre_classifier": {
          "type": "boolean",
          "title": "Enable Pre-classifier",
          "description": "When true, a cheap classifier scores each message before the orchestrator sees it. Low-complexity messages bypass orchestration entirely."
        },
        "classifier_model": {
          "type": "string",
          "minLength": 1,
          "title": "Classifier Executor",
          "description": "Name of the executor used as the complexity classifier. Must be defined in the `executors` section."
        },
        "complexity_threshold": {
          "type": "number",
          "minimum": 0,
          "maximum": 1,
          "title": "Complexity Threshold",
          "description": "Classifier score (0–1) below which a message is routed directly to the quick executor, skipping full orchestration. 0.6 is a sensible starting point."
        }
      },
      "required": [
        "pre_classifier",
        "classifier_model",
        "complexity_threshold"
      ],
      "additionalProperties": false,
      "title": "Routing",
      "description": "Pre-classifier and complexity-threshold routing settings."
    },
    "budgets": {
      "type": "object",
      "properties": {
        "daily_limit_usd": {
          "type": "number",
          "exclusiveMinimum": 0,
          "title": "Daily Limit (USD)",
          "description": "Maximum total LLM spend per calendar day across all sessions and users."
        },
        "per_task_limit_usd": {
          "type": "number",
          "exclusiveMinimum": 0,
          "title": "Per-task Limit (USD)",
          "description": "Hard ceiling on the cost of a single task execution. Protects against runaway orchestration chains."
        },
        "warning_threshold": {
          "type": "number",
          "minimum": 0,
          "maximum": 1,
          "title": "Warning Threshold",
          "description": "Fraction of the daily limit (0–1) at which a warning is emitted in logs. 0.8 warns at 80% usage."
        },
        "per_model_limits": {
          "type": "object",
          "additionalProperties": {
            "type": "number",
            "exclusiveMinimum": 0
          },
          "title": "Per-model Limits",
          "description": "Optional per-model daily spending caps keyed by fully-qualified model string.",
          "x-alduin-advanced": true
        }
      },
      "required": [
        "daily_limit_usd",
        "per_task_limit_usd",
        "warning_threshold"
      ],
      "additionalProperties": false,
      "title": "Budgets",
      "description": "Spending limits enforced before any LLM call is dispatched."
    },
    "fallbacks": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "title": "Fallback Chains",
      "description": "Ordered fallback model lists keyed by primary model string. When a model fails (rate limit, outage), the next in the list is tried in order.",
      "x-alduin-advanced": true
    },
    "memory": {
      "type": "object",
      "properties": {
        "hot_turns": {
          "type": "integer",
          "exclusiveMinimum": 0,
          "title": "Hot Turns",
          "description": "Number of recent conversation turns kept directly in the orchestrator context."
        },
        "warm_max_tokens": {
          "type": "number",
          "exclusiveMinimum": 0,
          "title": "Warm Summary Max Tokens",
          "description": "Token budget for the rolling warm-memory summary. Older content is compressed when this limit is reached.",
          "x-alduin-advanced": true
        },
        "cold_enabled": {
          "type": "boolean",
          "title": "Cold Memory Enabled",
          "description": "When true, older turns are embedded and stored for semantic retrieval from a vector database.",
          "x-alduin-advanced": true
        },
        "cold_embedding_model": {
          "type": "string",
          "title": "Embedding Model",
          "description": "Fully-qualified model string used to generate cold-memory embeddings.",
          "x-alduin-advanced": true
        },
        "cold_similarity_threshold": {
          "type": "number",
          "minimum": 0,
          "maximum": 1,
          "title": "Cold Similarity Threshold",
          "description": "Minimum cosine similarity (0–1) required for cold-memory retrieval to return a result.",
          "x-alduin-advanced": true
        },
        "redact_pii": {
          "type": "boolean",
          "title": "Redact PII",
          "description": "Also redact emails and phone numbers when promoting turns to warm/cold memory. API keys and JWTs are always redacted.",
          "x-alduin-advanced": true
        }
      },
      "required": [
        "hot_turns",
        "warm_max_tokens",
        "cold_enabled"
      ],
      "additionalProperties": false,
      "title": "Memory",
      "description": "Tiered memory configuration: hot (in-context turns) → warm (rolling summary) → cold (vector retrieval)."
    },
    "channels": {
      "type": "object",
      "properties": {
        "telegram": {
          "type": "object",
          "properties": {
            "enabled": {
              "type": "boolean",
              "title": "Enabled",
              "description": "Activates the Telegram channel adapter."
            },
            "mode": {
              "type": "string",
              "enum": [
                "webhook",
                "longpoll"
              ],
              "title": "Polling Mode",
              "description": "\"longpoll\" — bot polls Telegram (no public URL required, slightly higher latency). \"webhook\" — Telegram pushes updates to your HTTPS endpoint (faster, requires a reachable public URL)."
            },
            "token_env": {
              "type": "string",
              "minLength": 1,
              "title": "Bot Token Env Var",
              "description": "Name of the environment variable holding the Telegram bot token from @BotFather.",
              "x-alduin-sensitive": true
            },
            "webhook_url": {
              "type": "string",
              "format": "uri",
              "title": "Webhook URL",
              "description": "Public HTTPS URL Telegram will POST updates to. Required in webhook mode."
            },
            "webhook_secret_env": {
              "type": "string",
              "title": "Webhook Secret Env Var",
              "description": "Name of the environment variable holding the webhook secret token used to verify Telegram requests.",
              "x-alduin-sensitive": true
            },
            "allowed_user_ids": {
              "type": "array",
              "items": {
                "type": "number"
              }
            }
          },
          "required": [
            "enabled",
            "mode",
            "token_env"
          ],
          "additionalProperties": false,
          "title": "Telegram",
          "description": "Telegram bot channel."
        }
      },
      "additionalProperties": false,
      "title": "Channels",
      "description": "Messaging channel adapters."
    },
    "tenants": {
      "type": "object",
      "properties": {
        "default_tenant_id": {
          "type": "string",
          "minLength": 1,
          "title": "Default Tenant ID",
          "description": "Tenant identifier applied when an incoming event carries no tenant context.",
          "x-alduin-advanced": true
        }
      },
      "required": [
        "default_tenant_id"
      ],
      "additionalProperties": false,
      "title": "Tenants",
      "description": "Multi-tenant deployment isolation.",
      "x-alduin-advanced": true
    },
    "ingestion": {
      "type": "object",
      "properties": {
        "max_bytes": {
          "type": "integer",
          "exclusiveMinimum": 0,
          "title": "Max File Size (bytes)",
          "description": "Maximum allowed attachment size. Attachments exceeding this are rejected. Default: 25 MB.",
          "x-alduin-advanced": true
        },
        "ocr_enabled": {
          "type": "boolean",
          "title": "OCR Enabled",
          "description": "Enable optical character recognition for image attachments. Requires the optional tesseract.js peer dependency.",
          "x-alduin-advanced": true
        },
        "stt_enabled": {
          "type": "boolean",
          "title": "Speech-to-Text Enabled",
          "description": "Enable transcription for voice/audio attachments via OpenAI Whisper.",
          "x-alduin-advanced": true
        },
        "attachment_timeout_ms": {
          "type": "integer",
          "exclusiveMinimum": 0,
          "title": "Attachment Timeout (ms)",
          "description": "Per-attachment pipeline timeout. Attachments that take longer to process are rejected.",
          "x-alduin-advanced": true
        },
        "ttl_hours": {
          "type": "integer",
          "exclusiveMinimum": 0,
          "title": "Blob TTL (hours)",
          "description": "How long attachment blobs are retained in the store before the cleanup sweep removes them.",
          "x-alduin-advanced": true
        },
        "local_root": {
          "type": "string",
          "title": "Local Ingestion Root",
          "description": "Filesystem path prefix allowed for local file ingestion. Only files under this directory can be read. Requires ALDUIN_ALLOW_LOCAL_INGESTION=1.",
          "x-alduin-advanced": true
        }
      },
      "additionalProperties": false,
      "title": "Attachment Ingestion",
      "description": "Pipeline settings for files, images, and audio sent to the bot.",
      "x-alduin-advanced": true
    },
    "plugins": {
      "type": "object",
      "properties": {
        "local": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false
    },
    "auth": {
      "type": "object",
      "properties": {
        "privileged_bypass_budgets": {
          "type": "boolean",
          "default": false
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "orchestrator",
    "executors",
    "providers",
    "routing",
    "budgets"
  ],
  "additionalProperties": false,
  "$schema": "http://json-schema.org/draft-07/schema#"
};
